spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pegasus
    driver-class-name: org.postgresql.Driver
    username: pegasus
    password: pegasus

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

    hibernate:
      ddl-auto: update
