spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pegasus
    driver-class-name: org.postgresql.Driver
    username: pegasus
    password: pegasus
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        type: trace